### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by atsushiminamizuru** [atsushiminamizuru/protospace-38995#1]
自身のProtoSpaceのURL（本番環境）
https://protospace-38995-hfiw.onrender.com/

**Comment by shodai-ito** [comment]
@atsushiminamizuru さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
